In [32]:
import pandas as pd
import torch
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
df=pd.read_excel('comunications.xlsx')
df2=pd.read_csv('ChatbotData .csv')
df3=pd.read_excel('웰니스_대화_스크립트_데이터셋.xlsx')

print(df)
print(df2)
print(df3)
df2.drop(['label'], axis=1,inplace=True)
df3.drop(['구분'],axis=1, inplace=True)
df3.rename(columns = {'유저' : 'Q','챗봇':'A'}, inplace = True)
print(df3)
df1=pd.concat([df,df2])
print(df1)
df_final=pd.concat([df1,df3])
print(df_final.info())
df_final.dropna(axis=0, inplace=True)
print(df_final.info())


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\playg\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


                  A             Q
0            반갑습니다.        좋은 아침.
1         좋은 아침이에요.        좋은 아침.
2      간밤에 별일 없으셨죠?        좋은 아침.
3          안녕하시렵니까?        좋은 아침.
4            안녕하세요!        좋은 아침.
...             ...           ...
1319   네, 눈길 조심하세요.    눈 오는것 같은데?
1320    기분 좋은 하루에요.  너는 오늘 기분 어때?
1321  아무 생각도 안하는걸요.       무슨 생각해?
1322       잘 모르겠어요.         넌 뭐야?
1323    무슨 일 있으신가요?    기분이 영 별로야.

[1324 rows x 2 columns]
                             Q                         A  label
0                       12시 땡!                하루가 또 가네요.      0
1                  1지망 학교 떨어졌어                 위로해 드립니다.      0
2                 3박4일 놀러가고 싶다               여행은 언제나 좋죠.      0
3              3박4일 정도 놀러가고 싶다               여행은 언제나 좋죠.      0
4                      PPL 심하네                눈살이 찌푸려지죠.      0
...                        ...                       ...    ...
11818           훔쳐보는 것도 눈치 보임.        티가 나니까 눈치가 보이는 거죠!      2
11819           훔쳐보는 것도 눈치 보임.             훔쳐보는 거 티나나봐요

In [18]:
import pandas as pd
import torch
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
df=pd.read_excel('comunications.xlsx')
word_tokenize(df['Q'][1])

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\playg\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['좋은', '아침', '.']

In [9]:
import pandas as pd
import torch
import nltk
from eunjeon import Mecab
df=pd.read_excel('comunications.xlsx')
tokenizer=Mecab()
print(tokenizer.morphs(df['A'][1000])) # 형태소 분리


['기분', '도', '좋', '으셨으면', '좋', '겠', '어요', '.']


In [14]:
import pandas as pd
import torch
import nltk
from eunjeon import Mecab
import numpy as np
from nltk import FreqDist
df=pd.read_excel('comunications.xlsx')
# 데이터 정제
df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
print(df[:10])
tokenizer=Mecab()
tokenized=[]
# 데이터 전체 토큰화 
for sentence in df['Q']:
    temp=tokenizer.morphs(sentence)
    tokenized.append(temp)
print(tokenized[:10])
tokenized2=[]
for sentence in df['A']:
    temp2=tokenizer.morphs(sentence)
    tokenized2.append(temp2)
print(tokenized2[:10])
vocab=FreqDist(np.hstack(tokenized))
print('단어 집합의 크기',len(vocab))
vocab['좋']

             A      Q
0        반갑습니다  좋은 아침
1     좋은 아침이에요  좋은 아침
2  간밤에 별일 없으셨죠  좋은 아침
3      안녕하시렵니까  좋은 아침
4        안녕하세요  좋은 아침
5        안녕하세요  좋은 아침
6        안녕하세요   굿 모닝
7        반갑습니다   굿 모닝
8     좋은 아침이에요   굿 모닝
9  간밤에 별일 없으셨죠   굿 모닝
[['좋', '은', '아침'], ['좋', '은', '아침'], ['좋', '은', '아침'], ['좋', '은', '아침'], ['좋', '은', '아침'], ['좋', '은', '아침'], ['굿', '모닝'], ['굿', '모닝'], ['굿', '모닝'], ['굿', '모닝']]
[['반갑', '습니다'], ['좋', '은', '아침', '이', '에요'], ['간밤', '에', '별일', '없', '으셨', '죠'], ['안녕', '하', '시', '렵니까'], ['안녕', '하', '세요'], ['안녕', '하', '세요'], ['안녕', '하', '세요'], ['반갑', '습니다'], ['좋', '은', '아침', '이', '에요'], ['간밤', '에', '별일', '없', '으셨', '죠']]
단어 집합의 크기 260


<ipython-input-14-22f7636a981d>:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
<ipython-input-14-22f7636a981d>:10: FutureWarning: The default value of regex will change from True to False in a future version.
  df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")


172

In [15]:
import pandas as pd
import torch
import nltk
from eunjeon import Mecab
import numpy as np
from nltk import FreqDist
df=pd.read_excel('comunications.xlsx')
question,answer=list(df['Q']),list(df['A'])
question
answer

['반갑습니다.',
 '좋은 아침이에요.',
 '간밤에 별일 없으셨죠?',
 '안녕하시렵니까?',
 '안녕하세요!',
 '안녕하세요?',
 '안녕하세요.',
 '반갑습니다.',
 '좋은 아침이에요.',
 '간밤에 별일 없으셨죠?',
 '안녕하시렵니까?',
 '안녕하세요!',
 '안녕하세요?',
 '안녕하세요.',
 '반갑습니다.',
 '좋은 아침이에요.',
 '간밤에 별일 없으셨죠?',
 '안녕하시렵니까?',
 '안녕하세요!',
 '안녕하세요?',
 '안녕하세요.',
 '반갑습니다.',
 '좋은 아침이에요.',
 '간밤에 별일 없으셨죠?',
 '안녕하시렵니까?',
 '안녕하세요!',
 '안녕하세요?',
 '천만에요.',
 '천만에요.',
 '천만에요.',
 '아니에요.',
 '아니에요.',
 '아니에요.',
 '별 말씀을요.',
 '별 말씀을요.',
 '별 말씀을요.',
 '천만에요.',
 '별 말씀을요.',
 '아니에요.',
 '천만에요.',
 '별 말씀을요.',
 '아니에요.',
 '기운 내세요.',
 '남은 시간도 힘내서 마무리 하세요.',
 '네, 쉬었다가 하세요.',
 '얼마 안남았어요, 힘내세요.',
 '좋은 생각이에요.',
 '좋은 생각입니다.',
 '기운 내세요.',
 '남은 시간도 힘내서 마무리 하세요.',
 '네, 쉬었다가 하세요.',
 '얼마 안남았어요, 힘내세요.',
 '좋은 생각이에요.',
 '좋은 생각입니다.',
 '기운 내세요.',
 '남은 시간도 힘내서 마무리 하세요.',
 '네, 쉬었다가 하세요.',
 '얼마 안남았어요, 힘내세요.',
 '좋은 생각이에요.',
 '좋은 생각입니다.',
 '기운 내세요.',
 '남은 시간도 힘내서 마무리 하세요.',
 '네, 쉬었다가 하세요.',
 '얼마 안남았어요, 힘내세요.',
 '좋은 생각이에요.',
 '좋은 생각입니다.',
 '기운 내세요.',
 '남은 시간도 힘내서 마무리 하세요.',
 '네, 쉬었다가 하세요.',
 '얼마 안남았어요, 힘내세요.',
 '좋은 생각이에요.',
 '좋은 생각입

In [5]:
import pandas as pd
import torch
import nltk
from eunjeon import Mecab
import numpy as np
from nltk import FreqDist
from torchtext.legacy import data,datasets
import os
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
df=pd.read_excel('comunications.xlsx')
tokenizer=Mecab()
question,answer=df['Q'],df['A']

PAD, BOS, EOS = 1, 2, 3

class DataLoader():

    def __init__(self,
                 train_fn=None,
                 valid_fn=None,
                 exts=None,
                 batch_size=64,
                 device='cpu',
                 max_vocab=99999999,
                 max_length=255,
                 fix_length=None,
                 use_bos=True,
                 use_eos=True,
                 shuffle=True,
                 dsl=False
                 ):

        super(DataLoader, self).__init__()

        self.src = data.Field(
            sequential=True,
            use_vocab=True,
            batch_first=True,
            include_lengths=True,
            fix_length=fix_length,
            init_token='<BOS>' if dsl else None,
            eos_token='<EOS>' if dsl else None,
        )

        self.tgt = data.Field(
            sequential=True,
            use_vocab=True,
            batch_first=True,
            include_lengths=True,
            fix_length=fix_length,
            init_token='<BOS>' if use_bos else None,
            eos_token='<EOS>' if use_eos else None,
        )

        if train_fn is not None and valid_fn is not None and exts is not None:
            train = TranslationDataset(
                path=train_fn,
                exts=exts,
                fields=[('src', self.src), ('tgt', self.tgt)],
                max_length=max_length
            )
            valid = TranslationDataset(
                path=valid_fn,
                exts=exts,
                fields=[('src', self.src), ('tgt', self.tgt)],
                max_length=max_length,
            )

            self.train_iter = data.BucketIterator(
                train,
                batch_size=batch_size,
                device='cuda:%d' % device if device >= 0 else 'cpu',
                shuffle=shuffle,
                sort_key=lambda x: len(x.tgt) + (max_length * len(x.src)),
                sort_within_batch=True,
            )
            self.valid_iter = data.BucketIterator(
                valid,
                batch_size=batch_size,
                device='cuda:%d' % device if device >= 0 else 'cpu',
                shuffle=False,
                sort_key=lambda x: len(x.tgt) + (max_length * len(x.src)),
                sort_within_batch=True,
            )

            self.src.build_vocab(train, max_size=max_vocab)
            self.tgt.build_vocab(train, max_size=max_vocab)

    def load_vocab(self, src_vocab, tgt_vocab):
        self.src.vocab = src_vocab
        self.tgt.vocab = tgt_vocab


class TranslationDataset(data.Dataset):
    """Defines a dataset for machine translation."""

    @staticmethod
    def sort_key(ex):
        return data.interleave_keys(len(ex.src), len(ex.trg))

    def __init__(self, path, exts, fields, max_length=None, **kwargs):
        """Create a TranslationDataset given paths and fields.
        Arguments:
            path: Common prefix of paths to the data files for both languages.
            exts: A tuple containing the extension to path for each language.
            fields: A tuple containing the fields that will be used for data
                in each language.
            Remaining keyword arguments: Passed to the constructor of
                data.Dataset.
        """
        if not isinstance(fields[0], (tuple, list)):
            fields = [('src', fields[0]), ('trg', fields[1])]

        if not path.endswith('.'):
            path += '.'

        src_path, trg_path = tuple(os.path.expanduser(path + x) for x in exts)

        examples = []
        with open(src_path, encoding='utf-8') as src_file, open(trg_path, encoding='utf-8') as trg_file:
            for src_line, trg_line in zip(src_file, trg_file):
                src_line, trg_line = src_line.strip(), trg_line.strip()
                if max_length and max_length < max(len(src_line.split()), len(trg_line.split())):
                    continue
                if src_line != '' and trg_line != '':
                    examples += [data.Example.fromlist([src_line, trg_line], fields)]

        super().__init__(examples, fields, **kwargs)


<bound method DataLoader.load_vocab of <__main__.DataLoader object at 0x000001E1FE82EA60>>

In [43]:
import pandas as pd
import torch
import nltk
from eunjeon import Mecab
import numpy as np
from nltk import FreqDist
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
from gensim.models import Word2Vec
df=pd.read_excel('comunications.xlsx')
train_df=df[:1000]
test_df=df[1000:]
train_df.to_csv("train_data.csv",index=False)
test_df.to_csv("test_data.csv",index=False)
tokenizer=Mecab()
# 필드를 질문과 응답으로 구성함. 질문 타입과 대답 타입으로 구성. 
question=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs,lower=True, batch_first=True ,fix_length=20)
answer=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs, lower=True, batch_first=True, fix_length=20)
train_data, test_data=TabularDataset.splits(path='.',train='train_data.csv',test='test_data.csv',format='csv',fields=[('answer',answer),('question',question)],skip_header=True)
print(len(train_data))
print(train_data[0])
print(vars(train_data[0]))
print(train_df['Q'][0])
tokenizer=Mecab()
# 질문  모두 리스트로 합치기 임베딩용
resultQ=[]
for i in range (0,len(train_df['Q'])):
    temp=tokenizer.morphs(train_df['Q'][i])
    resultQ.append(temp)

#  응답 모두 리스트로 합치기 임베딩용

resultA=[]
for i in range (0,len(train_df['A'])):
    temp=tokenizer.morphs(train_df['A'][i])
    resultA.append(temp)
    

# print(result)
# print(train_data.fields.items())
# 단어 사전 형성하기.
question.build_vocab(train_data,min_freq=1,max_size=1000)
answer.build_vocab(train_data,min_freq=1, max_size=1000)
print(len(question.vocab))
print(answer.vocab.stoi)
batch_size=5
# 데이터 로더 만들기
train_loader=Iterator(dataset=train_data, batch_size=batch_size)
test_loader=Iterator(dataset=test_data, batch_size=batch_size)
print(len(train_loader))
print(len(test_loader))
batch=next(iter(train_loader))
print(type(batch))
print(batch.question)
print(batch.answer)
print(resultA)
# word2vec모델
model=Word2Vec(resultA,vector_size=100, window=3, min_count=5, workers=4, sg=1)
model_result=model.wv.most_similar('맛있')
print(model_result)


1000
{'answer': ['반갑', '습니다', '.'], 'question': ['좋', '은', '아침', '.']}
좋은 아침.
179
defaultdict(<bound method Vocab._default_unk_index of <torchtext.legacy.vocab.Vocab object at 0x000001F59176ED30>>, {'<unk>': 0, '<pad>': 1, '.': 2, '?': 3, '하': 4, '는': 5, '은': 6, '을': 7, '세요': 8, '식사': 9, '것': 10, '좋': 11, '게': 12, '이': 13, '시': 14, '같': 15, '어떠세요': 16, '어요': 17, '도': 18, '맛있': 19, '나요': 20, '에요': 21, '점심': 22, '시간': 23, '쉬': 24, '가': 25, '오늘': 26, '있': 27, '네요': 28, '잘': 29, '휴식': 30, '건': 31, '드세요': 32, '었': 33, '남': 34, '입니다': 35, '잠시': 36, '오': 37, ',': 38, '괜찮': 39, '아요': 40, '에': 41, '어떠셨': 42, '짜장면': 43, '요': 44, '았': 45, '고': 46, '가지': 47, '스트레칭': 48, '조금': 49, '를': 50, '드': 51, '습니다': 52, '겠': 53, '되': 54, '생각': 55, '힘내': 56, '셨': 57, '든든': 58, '신': 59, '다가': 60, '으로': 61, '다녀오': 62, '산책': 63, '간식': 64, '떡볶이': 65, '어떠신가요': 66, '일': 67, '가요': 68, '고민': 69, '높일': 70, '다': 71, '면': 72, '수': 73, '어떨까': 74, '으신': 75, '의': 76, '저': 77, '즐거운': 78, '합니다': 79, '내일': 80, '더': 81, '비': 82

In [4]:
import pandas as pd
import torch
import nltk
from eunjeon import Mecab
import numpy as np
from nltk import FreqDist
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
from gensim.models import Word2Vec
df=pd.read_excel('comunications.xlsx')
train_df=df[:1000]
test_df=df[1000:]
tokenizer=Mecab()
# 질문  모두 리스트로 합치기 임베딩용
resultQ=[]
for i in range (0,len(train_df['Q'])):
    temp=tokenizer.morphs(train_df['Q'][i])
    resultQ.append(temp)

#  응답 모두 리스트로 합치기 임베딩용

resultA=[]
for i in range (0,len(train_df['A'])):
    temp=tokenizer.morphs(train_df['A'][i])
    resultA.append(temp)
# print(resultA)
# word2vec모델
model=Word2Vec(resultA,vector_size=100, window=3, min_count=5, workers=4, sg=1)
model_result=model.wv.most_similar('맛있')
print(model_result)
# print(resultQ)
# 질문 Word2Vec 모델
model2=Word2Vec(resultQ,vector_size=100, window=3, min_count=5, workers=4, sg=1)
model_result2=model2.wv.most_similar('오늘')
print(model_result2)

# print (model.similarity('좋', '하루')) 
# 질문 데이터 모델 저장. 대답 데이터 모델도 저장. 
model.wv.save_word2vec_format('./a_w2v')
model2.wv.save_word2vec_format('./q_w2v')


C:\Users\playg\anaconda3\envs\deeplearn\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


[('게', 0.9961855411529541), ('간단', 0.9958627820014954), ('드세요', 0.99577397108078), ('어떠신가요', 0.9957104325294495), ('오후', 0.9956824779510498), ('든든', 0.9956126809120178), ('식사', 0.9955787658691406), ('미세먼지', 0.9955157041549683), ('셨', 0.9955033659934998), ('?', 0.9954848885536194)]
[('알려', 0.9980618953704834), ('는지', 0.9978100657463074), ('얼마나', 0.9977707266807556), (',', 0.9977495074272156), ('미세먼지', 0.9976557493209839), ('좀', 0.9975813627243042), ('남', 0.9975441098213196), ('.', 0.9975363612174988), ('줘', 0.9975192546844482), ('가', 0.9975090026855469)]


In [28]:
from glove import Corpus, Glove
import pandas as pd
from eunjeon import Mecab

df=pd.read_excel('comunications.xlsx')
df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
train_df=df[:1000]
test_df=df[1000:]
tokenizer=Mecab()
# 질문  모두 리스트로 합치기 임베딩용
resultQ=[]
for i in range (0,len(train_df['Q'])):
    temp=tokenizer.morphs(train_df['Q'][i])
    resultQ.append(temp)

#  응답 모두 리스트로 합치기 임베딩용

resultA=[]
for i in range (0,len(train_df['A'])):
    temp=tokenizer.morphs(train_df['A'][i])
    resultA.append(temp)
# 단어들의 동시등장 확률 생성한다. 
corpus=Corpus()
corpus.fit(resultQ,window=2)
# 모델 생성
glove=Glove(no_components=100, learning_rate=0.05)
glove.fit(corpus.matrix,epochs=20, no_threads=4, verbose=True)
glove.add_dictionary(corpus.dictionary)
# 단어 사전 모델에 적용. 
rs1=glove.most_similar("알려")
print(rs1)
corpus2=Corpus()
corpus2.fit(resultA,window=5)
glove2=Glove(no_components=100, learning_rate=0.05)
glove2.fit(corpus2.matrix, epochs=10, no_threads=4, verbose=True)
glove2.add_dictionary(corpus2.dictionary)
rs2=glove2.most_similar('점심')
print(rs2)



Performing 20 training epochs with 4 threads
Epoch 0
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Epoch 6
Epoch 7
Epoch 8
Epoch 9
Epoch 10
Epoch 11
Epoch 12
Epoch 13
Epoch 14
Epoch 15
Epoch 16
Epoch 17
Epoch 18
Epoch 19
[('줄래', 0.35677031867893894), ('되게', 0.33648933174186596), ('참', 0.32340821915085755), ('다가', 0.31555349284900486)]
Performing 10 training epochs with 4 threads
Epoch 0
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Epoch 6
Epoch 7
Epoch 8
Epoch 9
[('식사', 0.9717774660910719), ('어떠셨', 0.9288128279067273), ('맛있', 0.9200957121166606), ('게', 0.889330711288972)]


<ipython-input-28-024f63fcf800>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
<ipython-input-28-024f63fcf800>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")


In [33]:
import pandas as pd
from eunjeon import Mecab
import torch.nn as nn
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
df=pd.read_excel('comunications.xlsx')
df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
train_df=df[:1000]
test_df=df[1000:]
tokenizer=Mecab()
train_df.to_csv("train_data.csv",index=False)
test_df.to_csv("test_data.csv",index=False)
tokenizer=Mecab()
# 필드를 질문과 응답으로 구성함. 질문 타입과 대답 타입으로 구성. 
question=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs,lower=True, batch_first=True ,fix_length=20)
answer=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs, lower=True, batch_first=True, fix_length=20)
train_data, test_data=TabularDataset.splits(path='.',train='train_data.csv',test='test_data.csv',format='csv',fields=[('answer',answer),('question',question)],skip_header=True)
# 단어 사전 형성하기.
question.build_vocab(train_data,min_freq=1,max_size=1000)
answer.build_vocab(train_data,min_freq=1, max_size=1000)
# 데이터 로더
batch_size=5
train_loader=Iterator(dataset=train_data, batch_size=batch_size)
test_loader=Iterator(dataset=test_data, batch_size=batch_size)
batch=next(iter(train_loader))
# 단어 사전 만들기 
# 질문 단어 사전.
vocab1=batch.question
# 대답 단어 사전
vocab2=batch.answer
# 임베딩벡터 생성(질문)
embedding_layer=nn.Embedding(num_embeddings=len(vocab1), embedding_dim=3, padding_idx=1)
print(embedding_layer.weight)
# 임베딩벡터 생성(대답)-> 파라미터 조정 필요. 
embedding_layer2=nn.Embedding(num_embeddings=len(vocab2), embedding_dim=5, padding_idx=1)
print(embedding_layer2.weight)

Parameter containing:
tensor([[-0.2908,  1.0967, -0.0461],
        [ 0.0000,  0.0000,  0.0000],
        [-0.5402,  0.0240, -1.4962],
        [ 0.3573,  0.1289,  0.5047],
        [-1.4362, -0.3271, -0.5391]], requires_grad=True)
Parameter containing:
tensor([[ 1.1250,  0.8226, -1.9138, -0.4423, -0.6329],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.3729, -0.5713,  1.1141,  1.3767,  0.5512],
        [ 0.7738,  0.6421,  0.5784,  2.3459,  0.4920],
        [-1.0384, -1.7440, -2.2862,  0.6735, -1.1327]], requires_grad=True)


<ipython-input-33-855a98870e04>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
<ipython-input-33-855a98870e04>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")


In [43]:
import pandas as pd
from eunjeon import Mecab
import torch.nn as nn
from torchtext.vocab import GloVe
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
df=pd.read_excel('comunications.xlsx')
df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
train_df=df[:1000]
test_df=df[1000:]
tokenizer=Mecab()
train_df.to_csv("train_data.csv",index=False)
test_df.to_csv("test_data.csv",index=False)
tokenizer=Mecab()
# 필드를 질문과 응답으로 구성함. 질문 타입과 대답 타입으로 구성. 
question=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs,lower=True, batch_first=True ,fix_length=20)
answer=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs, lower=True, batch_first=True, fix_length=20)
train_data, test_data=TabularDataset.splits(path='.',train='train_data.csv',test='test_data.csv',format='csv',fields=[('answer',answer),('question',question)],skip_header=True)
# 단어 사전 형성하기.
question.build_vocab(train_data,vectors=GloVe(name='6B',dim=300),min_freq=1,max_size=1000)
answer.build_vocab(train_data,vectors=GloVe(name='6B',dim=300),min_freq=1,max_size=1000)
print(question.vocab.stoi)
print(answer.vocab.vectors.shape)
# print(question.vocab.vectors[0])
# print(question.vocab.vectors[1])
# print(question.vocab.vectors[8])
embedding_layer=nn.Embedding.from_pretrained(question.vocab.vectors, freeze=False)
embedding_layer(torch.LongTensor([8]))
# 결과가 안 나오는 이유. 사전에 훈련된 glove에 한글이 없다. 영어로만 되어 있다. 

<ipython-input-43-a0c4a5372568>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
<ipython-input-43-a0c4a5372568>:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")


defaultdict(<bound method Vocab._default_unk_index of <torchtext.legacy.vocab.Vocab object at 0x0000025298A97640>>, {'<unk>': 0, '<pad>': 1, '오늘': 2, '다': 3, '은': 4, '먹': 5, '이': 6, '좋': 7, '뭐': 8, '아': 9, '어': 10, '는': 11, '피곤': 12, '좀': 13, '을까': 14, '네': 15, '너무': 16, '점심': 17, '하': 18, '배부르': 19, '지': 20, '잘': 21, '었': 22, '게': 23, '겠': 24, '안': 25, '같': 26, '것': 27, '집중': 28, '야': 29, '너': 30, '가': 31, '그거': 32, '날씨': 33, '따라': 34, '생각': 35, '응': 36, '돼': 37, '다가': 38, '쉬': 39, '미세먼지': 40, '고': 41, '되': 42, '알려줘': 43, '배불러': 44, '왔': 45, '집중력': 46, '해야': 47, '으로': 48, '어디': 49, '니': 50, '어때': 51, '짜장면': 52, '그래': 53, '지금': 54, '퇴근': 55, '해': 56, '언': 57, '컴': 58, '패니': 59, '별로': 60, '진짜': 61, '그게': 62, '그래야': 63, '남': 64, '았': 65, '얼마나': 66, '오': 67, '이름': 68, '참': 69, '겠다': 70, '어야': 71, '에': 72, '였': 73, '내일': 74, '떨어지': 75, '많이': 76, '한': 77, '흐려': 78, '도': 79, '배고프': 80, '안녕': 81, '낫': 82, '다시': 83, '배': 84, '쉬엄': 85, '넌': 86, '있': 87, '농도': 88, '아침': 89, '어떤지': 90, '완전': 91, 

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [15]:
import torch
from eunjeon import Mecab
import torch.nn as nn
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
import pandas as pd
input_size=5
hidden_size=8
inputs=torch.Tensor(1,10,5)
cell=nn.RNN(input_size, hidden_size, batch_first=True)
outputs, _status=cell(inputs) # 입력 텐서를 집어넣어서, 결과 확인
# 첫번째 값은 모든시점의 은닉상태, 두번째는 마지막 시점의 은닉상태
print(outputs.shape)# 전체 은닉 값.
print(_status.shape) # 마지막의 은닉값
# RNN 계층 여러개인 경우
inputs2=torch.Tensor(1,10,5)
cell2=nn.RNN(input_size=5, hidden_size=8, num_layers=2, batch_first=True)
outputs2, _status2=cell2(inputs2)
print(outputs2.shape)
print(_status2.shape)
# 양방향 RNN
inputs3=torch.Tensor(1,10,5)
cell3=nn.RNN(input_size=5, hidden_size=8, num_layers=2, batch_first=True,bidirectional=True)
outputs3, _status3=cell3(inputs3)
print(outputs3.shape)
print(_status3.shape)
# LSTM 
cell4=nn.LSTM(input_size=5, hidden_size=8, num_layers=4, batch_first=True)
outputs4,_status4=cell4(inputs3)
print(outputs4.shape)
print(_status4)

df=pd.read_excel('comunications.xlsx')
df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
train_df=df[:1000]
test_df=df[1000:]
tokenizer=Mecab()
train_df.to_csv("train_data.csv",index=False)
test_df.to_csv("test_data.csv",index=False)
tokenizer=Mecab()
# 필드를 질문과 응답으로 구성함. 질문 타입과 대답 타입으로 구성. 
question=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs,lower=True, batch_first=True ,fix_length=20)
answer=data.Field(sequential=True, use_vocab=True, tokenize=tokenizer.morphs, lower=True, batch_first=True, fix_length=20)
train_data, test_data=TabularDataset.splits(path='.',train='train_data.csv',test='test_data.csv',format='csv',fields=[('answer',answer),('question',question)],skip_header=True)
# 단어 사전 형성하기.
question.build_vocab(train_data,min_freq=1,max_size=1000)
answer.build_vocab(train_data,min_freq=1,max_size=1000)
vocab_q=dict(question.vocab.stoi)
vocab_a=dict(answer.vocab.stoi)


torch.Size([1, 10, 8])
torch.Size([1, 1, 8])
torch.Size([1, 10, 8])
torch.Size([2, 1, 8])
torch.Size([1, 10, 16])
torch.Size([4, 1, 8])
torch.Size([1, 10, 8])
(tensor([[[ 0.0000,  0.0000,  0.9640,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000]],

        [[-0.2069,  0.1040,  0.0389, -0.1088, -0.1885, -0.0425,  0.0064,
          -0.0551]],

        [[ 0.1269, -0.0616, -0.0086, -0.1208,  0.0114, -0.1491, -0.1126,
           0.2394]],

        [[ 0.0562,  0.0951, -0.0595, -0.0307,  0.0977,  0.0439, -0.0639,
          -0.0600]]], grad_fn=<StackBackward>), tensor([[[ 0.0000,  0.0000,  2.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000]],

        [[-0.3883,  0.2126,  0.0670, -0.2567, -0.4063, -0.0812,  0.0133,
          -0.1063]],

        [[ 0.2717, -0.1046, -0.0180, -0.1996,  0.0291, -0.2996, -0.2154,
           0.5031]],

        [[ 0.0857,  0.1829, -0.1040, -0.0595,  0.1703,  0.0878, -0.1480,
          -0.1251]]], grad_fn=<StackBackward>))


<ipython-input-15-57444b852060>:34: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Q'] = df['Q'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
<ipython-input-15-57444b852060>:35: FutureWarning: The default value of regex will change from True to False in a future version.
  df['A'] = df['A'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")


NameError: name 'GloVe' is not defined

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from eunjeon import Mecab
import torch.nn as nn
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
import pandas as pd
# 문자 단위 RNN 구현 예제
input_str = 'apple'
label_str = 'pple!'
char_vocab = sorted(list(set(input_str+label_str)))
vocab_size = len(char_vocab)
print ('문자 집합의 크기 : {}'.format(vocab_size))
input_size=vocab_size
# 단어 사전 형성
hidden_size=5
output_size=5
learning_rate=0.1
char_toindex=dict((c,i) for i, c in enumerate(char_vocab))
print(char_toindex)
index_to_char={}
for key, value in char_toindex.items():
    index_to_char[value] = key
print(index_to_char)
x_data = [char_toindex[c] for c in input_str]
y_data = [char_toindex[c] for c in label_str]
x_data=[x_data]
y_data=[y_data]
x_onehot=[np.eye(vocab_size)[x]for x in x_data]
# 텐서로 바꿔주기. 
x=torch.FloatTensor(x_onehot)
y=torch.LongTensor(y_data)
print(x.shape)
print(y.shape)
# 모델 구현
class Net(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Net,self).__init__()
        self.rnn=torch.nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc=torch.nn.Linear(hidden_size, output_size, bias=True)
    def forward(self, x):
        x,_status=self.rnn(x)
        x=self.fc(x)
        return x
net=Net(input_size, hidden_size, output_size)
outputs=net(x)
print(outputs.shape)
# 펼치기
print(outputs.view(-1, input_size).shape)
print(y.shape)
print(y.view(-1).shape)
# 손실함수 정의
criterion=torch.nn.CrossEntropyLoss()
optimizer=optim.Adam(net.parameters(),learning_rate)
# 반복 학습을 통해서 학습
for i in range(100):
    optimizer.zero_grad()
    outputs=net(x)
    # 배치 차원 제거
    loss=criterion(outputs.view(-1,input_size),y.view(-1))
    loss.backward() # 기울기 계산
    optimizer.step() # 파라미터들 업데이트
    result=outputs.data.numpy().argmax(axis=2) # 제일 높은 인덱스 return
    result_str = ''.join([index_to_char[c] for c in np.squeeze(result)]) # 단어 사전 통해서 단어로 복원. 
    print(i, "loss(crossentropy) ", loss.item(), "prediction word ", result, "true Y: ", y_data, "prediction str: ", result_str)


문자 집합의 크기 : 5
{'!': 0, 'a': 1, 'e': 2, 'l': 3, 'p': 4}
{0: '!', 1: 'a', 2: 'e', 3: 'l', 4: 'p'}
torch.Size([1, 5, 5])
torch.Size([1, 5])
torch.Size([1, 5, 5])
torch.Size([5, 5])
torch.Size([1, 5])
torch.Size([5])
0 loss(crossentropy)  1.7881288528442383 prediction word  [[1 1 1 1 1]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  aaaaa
1 loss(crossentropy)  1.5113601684570312 prediction word  [[3 2 3 2 2]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  lelee
2 loss(crossentropy)  1.3133808374404907 prediction word  [[4 4 3 2 2]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pplee
3 loss(crossentropy)  1.1266353130340576 prediction word  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
4 loss(crossentropy)  0.9002696871757507 prediction word  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
5 loss(crossentropy)  0.6846823692321777 prediction word  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
6 loss(crossentropy)  0.5091173052787781 prediction wor

In [30]:
import torch
import torch.nn as nn
import torch.optim as optim
from eunjeon import Mecab
from torchtext.legacy import data,datasets
from torchtext.legacy.data import  TabularDataset, BucketIterator, Iterator
import pandas as pd
df=pd.read_excel('comunications.xlsx')
train_df=df[:1000]
test_df=df[1000:]
tokenizer=Mecab()
train_df.to_csv("train_data.csv",index=False)
test_df.to_csv("test_data.csv",index=False)
tokenizer=Mecab()
print(train_df['A'][740])
sentence=train_df['A'][740]
vocab=tokenizer.morphs(sentence)
print(vocab)
word2index={token: i for i, token in enumerate(vocab,1)}
word2index['<unk>']=0
print(word2index)
print(word2index['오늘'])
index2word={v:k for k, v in word2index.items()}
print(index2word)
print(index2word[0])
# 정수로 인코딩과, 입력 데이터와 레이블 데이터 만드는 함수
def prepare(sentence, word2index):
    encoded=[word2index[token] for token in tokenizer.morphs(sentence)]
    input_seq,label_seq=encoded[:-1],encoded[1:]
    input_seq=torch.LongTensor(input_seq).unsqueeze(0)
    label_seq=torch.LongTensor(label_seq).unsqueeze(0)
    return input_seq,label_seq
x,y=prepare(sentence, word2index)
print(x)
print(y)
class Net(nn.Module):
    def __init__(self, vocab_size, input_size, hidden_size, batch_first=True):
        super(Net, self).__init__()
        # 임베딩하는 함수
        self.embedding_layer=nn.Embedding(num_embeddings=vocab_size, embedding_dim=input_size)
        # 입력 차원
        self.rnn_layer=nn.RNN(input_size, hidden_size,batch_first=batch_first)
        # 출력 차원
        self.linear=nn.Linear(hidden_size, vocab_size)
    def forward(self,x):
        output=self.embedding_layer(x)
        output,hidden=self.rnn_layer(output)
        output=self.linear(output)
        return output.view(-1,output.size(2))
vocab_size=len(word2index)
input_size=5
hidden_size=20
model=Net(vocab_size, input_size, hidden_size, batch_first=True)
# 손실함수
loss_func=nn.CrossEntropyLoss()
optimizer=optim.Adam(params=model.parameters())
output=model(x)
print(output)
print(output.shape)
# 숫자를 단어로 복원
decode=lambda y:[index2word.get(x) for x in y]
for step in range(201):
    optimizer.zero_grad()
    output=model(x)
    loss=loss_func(output,y.view(-1))
    loss.backward()
    optimizer.step()
    if step % 40==0:
        print("[{:02d}/201]{:.4f}".format(step+1,loss))
        pred=output.softmax(-1).argmax(-1).tolist()
        print(" ".join(['오늘']+decode(pred)))
        print()

오늘은 비가 오니 곱창전골 어떠세요?
['오늘', '은', '비', '가', '오', '니', '곱창전골', '어떠세요', '?']
{'오늘': 1, '은': 2, '비': 3, '가': 4, '오': 5, '니': 6, '곱창전골': 7, '어떠세요': 8, '?': 9, '<unk>': 0}
1
{1: '오늘', 2: '은', 3: '비', 4: '가', 5: '오', 6: '니', 7: '곱창전골', 8: '어떠세요', 9: '?', 0: '<unk>'}
<unk>
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
tensor([[2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[ 0.0088, -0.0147,  0.1904,  0.2530,  0.1657,  0.4203,  0.0432, -0.1511,
         -0.2922,  0.3333],
        [-0.0911,  0.0305, -0.3431,  0.4494, -0.0075,  0.1878, -0.1342,  0.1038,
          0.1585, -0.2280],
        [ 0.1445,  0.2462, -0.1810,  0.3516, -0.2399,  0.2356,  0.2240, -0.0662,
          0.0331, -0.3196],
        [-0.1349,  0.0924,  0.0555,  0.2504, -0.0012,  0.1068,  0.0519, -0.0269,
          0.1072, -0.2276],
        [ 0.1387,  0.4945,  0.1004, -0.1386, -0.1936, -0.0631,  0.1539, -0.1190,
         -0.0306, -0.5424],
        [-0.2033,  0.2794,  0.1946, -0.1303, -0.1466,  0.2576,  0.0885, -0.1962,
         -0.1022, -0.4297],
        [ 

In [2]:
import torch
import os
import torch.nn as nn
import torch.nn.functional as f
from torchtext import data, datasets
import random
Seed=5
random.seed(Seed)
torch.manual_seed(Seed)
Batch_size=64
lr=0.001
epoch=10
USE_CUDA=torch.cuda.is_available()
# gpu로 사용이 되지 않아 cpu로 가능하다. 
DEVICE=torch.device("cuda" if USE_CUDA else "cpu")
print(DEVICE)
                    


cpu
